version: 2.1
orbs:
  node: circleci/node@4.3
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2.3.6

parameters:
  run_integration_tests:
    type: boolean
    default: false
  
jobs:
  build:
    macos:
      xcode: 15.2.0
    parameters:
      run_integration_tests:
        type: boolean      
    steps:
      - checkout
      - print:
          message: Printing << parameters.message >>

workflows:
  sample:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - build