version: 2.1
orbs:
  node: circleci/node@4.3
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2.3.6
  
jobs:
  build:
    macos:
      xcode: 15.2.0 

    steps:
      # Checkout the code as the first step.
      - checkout
      - run: pod install # Install CocoaPods dependencies
      - run: fastlane scan # Run tests using Fastlane
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  sample:
    jobs:
      - build
