version: 2.1
orbs:
  node: circleci/node@4.3
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2.3.6
  
jobs:
  build:
    macos:
      xcode: 15.2.0
    steps:
      - checkout

workflows:
  sample:
    jobs:
      - build
